export const pokemons = [
  { id: 'bulbasaur', name: 'Bulbasaur', image: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/1.png', color: '#7acfa0' },
  { id: 'ivysaur',  name: 'Ivysaur', image: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/2.png', color: '#4fa5ad' },
  { id: 'venusaur', name: 'Venusaur', image: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/3.png', color: '#4c9b84' },
  { id: 'charmander',  name: 'Charmander', image: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/4.png', color: '#f2e8c9' },
  { id: 'charmeleon',  name: 'Charmeleon', image: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/5.png', color: '#e88978' },
  { id: 'charizard',  name: 'Charizard', image: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/6.png', color: '#4298a8' },
  { id: 'squirtle',  name: 'Squirtle', image: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/7.png', color: '#75bdd0' },
  { id: 'wartortle',  name: 'Wartortle', image: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/8.png', color: '#9aaadd' },
  { id: 'blastoise',  name: 'Blastoise', image: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/9.png', color: '#6b9bd1' },
  { id: 'caterpie',  name: 'Caterpie', image: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/10.png', color: '#8fcf72' },
  { id: 'metapod',  name: 'Metapod', image: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/11.png', color: '#93b66c' },
  { id: 'butterfree',  name: 'Butterfree', image: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/12.png', color: '#b9a1d9' },
  { id: 'weedle',  name: 'Weedle', image: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/13.png', color: '#d39b72' },
  { id: 'kakuna',  name: 'Kakuna', image: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/14.png', color: '#c9ad63' },
  { id: 'beedrill',  name: 'Beedrill', image: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/15.png', color: '#d6bd4a' },
  { id: 'pidgey',  name: 'Pidgey', image: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/16.png', color: '#c9a979' },
  { id: 'pidgeotto',  name: 'Pidgeotto', image: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/17.png', color: '#c48f5d' },
  { id: 'pidgeot', name: 'Pidgeot', image: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/18.png', color: '#d1a45f' },
  { id: 'rattata',  name: 'Rattata', image: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/19.png', color: '#aa89c8' },
  { id: 'raticate',  name: 'Raticate', image: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/20.png', color: '#c9a16f' },
];